apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: dev
  labels:
    app: deploy-labelname
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-label
      podlabel: mypodlabel
  template:
    metadata:
      labels:
        app: nginx-label
        podlabel: mypodlabel
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

