apiVersion: v1
kind: Service
metadata:
  name: my-svc-lb
  namespace: dev
spec:
  selector:
    app: nginx-label
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
  externalIPs:
    - 172.31.71.37
