apiVersion: v1
kind: Service
metadata:
  name: mynodeport-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: nginx-label
  ports: 
    - port: 8080
      targetPort: 80
      nodePort: 30001

